### ISSUE TITLE
OAuth Console is missing on latest

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-dev#102]
https://oauth-latest.dev.lcip.org/console/ gives an error.

**Comment by vladikoff** [comment]
I had to manually apply the nginx config (from https://github.com/mozilla/fxa-dev/blob/master/roles/oauth-console/templates/upstream.conf.j2) to bring it back .

I assume this will happen if the oauth server is redeployed on its own, thus replacing the nginx config

**Comment by rfk** [comment]
@jrgm or @vladkoff did we find a proper resolution to this issue?  I seem to recall a fix being done but can't remember the details.

**Comment by jrgm** [comment]
Yeah, actually this was fixed in PR 114, but apparently putting 'fixes' in air quotes confused github, and this issue wasn't auto-closed ;-)
