### ISSUE TITLE
install npm@2 

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-dev#105]
WIll file a PR shortly, just filing this and some other to keep track while trying a scratch fxa-dev build.

Anything less than npm@2.1 is 1. flaky, and 2. unsupported. So upgrade from the version that comes with nodejs 0.10.x

**Comment by vladikoff** [comment]
It seems 2.4.1 is the current stable.

**Comment by jrgm** [comment]
@vladikoff - yeah. Do you think I should `pin` to a n.n.n version, or just say npm@2?
