### ISSUE TITLE
http -> https redirect

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-dev#118]
If you forget to specify `https://` when connecting to the server, you'll get timeouts/connectivity errors.  We should consider doing a redirect from http to https to avoid confusion.

**Comment by dannycoates** [comment]
I've been meaning to do this since forever... should be good as of now 80afa5cfab9a4ca2c3e56c5ea45f0fcce5d8770b

**Comment by dannycoates** [comment]
actually... this doesn't work yet. I was fooled by HSTS when I tested it. I'll need to add port 80 to the ELB cloudformation...

**Comment by dannycoates** [comment]
Sheesh, that was more of a pain than I thought. It should work now 5658c8481c8b96c12a6c78a2969ed2b32ba8affd

**Comment by rfk** [comment]
seems to work now
