### ISSUE TITLE
pip now installs supervisord into /usr/local/bin, but upstart is configured for /usr/bin

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-dev#135]
This is odd. Just built a box from scratch and it kept dying with 

```
TASK: [common | start supervisord] ******************************************** 
failed: [ec2-52-10-10-127.us-west-2.compute.amazonaws.com] => {"failed": true}
msg: start: Job failed to start
```

After looking, it appears that maybe `pip` is now installing into /usr/local/bin, so supervisord isnt' where initctl is looking for it. Weird.

**Comment by jrgm** [comment]
I'll look later, but thought I'd put this in before I forgot.

**Comment by shane-tomlinson** [comment]
My hacktastic "fix" was to ssh into the box and do:

```bash
sudo ln -s /usr/local/bin/supervisord /usr/bin/supervisord
```
