### ISSUE TITLE
Remove the need for separate "oauth-stable.*" domain

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-dev#152]
I sadly haven't paid enough attention to understand this: why do we need to host the oauth stuff on a separate domain like "oauth-stable.dev.lcip.org" rather than a sub-path like "stable.dev.lcip.org/oauth"?

It would be great to simplify the hosting here to avoid confusion for new RPs, who we regularly see stumble on knowing that services are on which hostname.

**Comment by vladikoff** [comment]
from mtg: kill it.
