### ISSUE TITLE
500 errors from the auth-server with `login?keys=true`

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-dev#158]
![image](https://cloud.githubusercontent.com/assets/128755/8387431/345807ac-1c0d-11e5-8903-bb8ad6b0952b.png)

To reproduce in `fxa-content-server` run:
`npm run test-latest  grep="Firefox Desktop Sync sign_in - sign in verified"`

**Comment by vladikoff** [comment]
cc @jrgm @dannycoates

**Comment by vladikoff** [comment]
the request times out after 6 seconds: 
![image](https://cloud.githubusercontent.com/assets/128755/8387499/c2e8108e-1c0d-11e5-9b0a-ab25546347a6.png)

**Comment by jrgm** [comment]
Yeah, so ran out of disk space again. I cleaned up some old logs (again). Basically, need a bigger drive.

Closing, since this is working again (fixed this about 3pm but didn't see this issue until now; up on a mountain, or something).

**Comment by vladikoff** [comment]
Thank you!
