### ISSUE TITLE
Retry on npm install errors

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-dev#161]
Any time there is an error installing from npm, no retry attempt is made, and the process aborts. You then have to start over from the beginning. It'll check & skip already done items, but sometimes it takes 20 minutes to get back to the point where the error occurred.

We should add some sort of retry mechanism, or use a more stable mirror, or something to make this better.

**Comment by vladikoff** [comment]
from mtg: npm has improved and it seems to be better now. we will do this if needed. cc @jrgm
