### ISSUE TITLE
Allow ssh to the public domain name

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-dev#162]
(capturing feedback from @shane-tomlinson)

If I set up a box with the name stomlinson.dev.lcip.org, I cannot ssh to stomlinson.dev.lcip.org, I have to ssh to ec2-52-26-160-90.us-west-2.compute.amazonaws.com. Finding that name, once ansible has completed its setup, requires that I go to the Amazon web console and look up the name.

We should just allow ssh to the configured domain name.

**Comment by vladikoff** [comment]
> We should just allow ssh to the configured domain name.

You have to ssh into `meta-stomlinson.dev.lcip.org` I think

**Comment by rfk** [comment]
Oh cool, thanks @vladikoff.  I added a little note to the readme here: https://github.com/mozilla/fxa-dev/commit/07e6e2fce808ac7df953bf90328fe05d9b749753

I remain baffled by the need for extra domains, but not baffled enough to actually try to find an alternative solution.

**Comment by jrgm** [comment]
Just to complete this a bit, `meta-stomlinson.dev.lcip.org` resolves directly to the EC2 instance built by the fxadev-stomlinson stack. `stomlinson.dev.lcip.org` resolves to an ELB that handles the SSL termination.
