### ISSUE TITLE
Use mozilla/fxa-content-experiments branches

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-dev#172]
fxa-dev should be using `train-XX-stage` branches. 
These branches will have experiment dates (will activate early, unlike production) adjusted so we can test if things activate properly (such as avatars, marketing links, etc). So when we bump train branches, the experiment branch should also be bumped.

![image](https://cloud.githubusercontent.com/assets/128755/8945742/24a8772e-3558-11e5-8249-10893dab3ac5.png)

cc @jrgm

**Comment by jrgm** [comment]
So that's a change in the config json for content-server, ya?

**Comment by shane-tomlinson** [comment]
I'm missing the need for the train-xxx-stage branches, is the normal
train-xxx insufficient for deployment onto an fxa-dev or stage stack?

**Comment by vladikoff** [comment]
> I'm missing the need for the train-xxx-stage branches, is the normal
train-xxx insufficient for deployment onto an fxa-dev or stage stack?

The goal here is for experiments to activate earlier in dev / stage than in prod. i.e the avatar link will start showing earlier so we do not get any surprises in production

**Comment by vladikoff** [comment]
> The goal here is for experiments to activate earlier in dev / stage than in prod. i.e the avatar link will start showing earlier so we do not get any surprises in production

And if we want for them to activate earlier then we need the branch with experiments to have different dates set for `startDate` or `endDate`

**Comment by dannycoates** [comment]
> The goal here is for experiments to activate earlier in dev / stage than in prod. i.e the avatar link will start showing earlier so we do not get any surprises in production

I understand the intent but the solution seems error prone. Its like juggling knives, everything is fine until you lose track of one.

Since the intent is to start experiments early on dev / stage, what if we just make experiments in those environments ignore the dates? Then we only need to worry about setting the dates relative to prod and stage can track the next prod branch.

**Comment by vladikoff** [comment]
>  Its like juggling knives, everything is fine until you lose track of one.

Totally agreed.
:hocho: :hocho: 
      :raised_hands:



> Since the intent is to start experiments early on dev / stage, what if we just make experiments in those environments ignore the dates? Then we only need to worry about setting the dates relative to prod and stage can track the next prod branch.

How can we ignore the dates?

:hocho:

**Comment by vladikoff** [comment]
> what if we just make experiments in those environments ignore the dates

did you mean that we would adjust the experiment code to basically `env === latest` ?

**Comment by vladikoff** [comment]
@jrgm note: do **not** use `train-XX-stage` branches for now
