### ISSUE TITLE
tag AWS instances

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-dev#173]
* Tag all resources you create with an "Owner" tag which is your @mozilla.com email address
* Tag long-running instances with REAPER_SPARE_ME

**Comment by vladikoff** [comment]
@dannycoates how important is this? we moved this to "backlog" from "triage" in waffle but feel free to move it up priority if needed

**Comment by dannycoates** [comment]
> how important is this?

Not very at the moment. Resources created with cloudformation aren't reaped.

**Comment by vladikoff** [comment]
and "tag" is AWS Instance Tag on EC2
