### ISSUE TITLE
cron update does not work with https://uxwip.dev.lcip.org

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-dev#177]
If we check https://uxwip.dev.lcip.org/ver.json
and 
https://github.com/mozilla/fxa-content-server/tree/issue-2336-new-settings-page

## Actual 

{"version":"0.41.1","commit":"fd8730708ce168ad9328b0add0560099d828addc","l10n":"ccd87e66f6","tosPp":"27d35cc967"}

## Expected

commit sha should be c1b947a0b537d33a3c82f2131de6666908c4e570

**Comment by jrgm** [comment]
From /var/spool/mail/ec2-user

X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/ec2-user>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=ec2-user>
X-Cron-Env: <USER=ec2-user>
Message-Id: <20150730145001.55F2437652@ip-172-31-15-39.localdomain>
Date: Thu, 30 Jul 2015 14:50:01 +0000 (UTC)

/bin/sh: ansible-playbook: command not found

----
$ which ansible-playbook
/usr/local/bin/ansible-playbook

---

So pip is now installing ansible-playbook into /usr/local/bin and that is not on the default path for cron.

I ran the cronjob manually, and now:
$ curl https://uxwip.dev.lcip.org/ver.json
{"version":"0.41.1","commit":"c1b947a0b537d33a3c82f2131de6666908c4e570","l10n":"ccd87e66f6","tosPp":"27d35cc967"}

But why pip has changed the install directory of some packages is a mystery.

I did `sudo ln -s /usr/local/bin/ansible-playbook /usr/bin/ansible-playbook` so cron will work now on **this** box. But apparently we need to maybe do similar to https://github.com/mozilla/fxa-dev/commit/de5dbdedc752ac9df50904e765d8bddacaa5a391 and/or https://github.com/mozilla/fxa-dev/pull/175

**Comment by vladikoff** [comment]
Thanks for debugging this @jrgm !!

**Comment by vladikoff** [comment]
cc @dannycoates

**Comment by vladikoff** [comment]
This is fixed for uxwip
