### ISSUE TITLE
https://latest.dev.lcip.org/ is 500ing 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-dev#184]
![image](https://cloud.githubusercontent.com/assets/128755/9294771/4e741bea-4425-11e5-9ed1-930786ba7239.png)
![image](https://cloud.githubusercontent.com/assets/128755/9294777/5f930bc0-4425-11e5-881e-fd64d0e18846.png)

**Comment by vladikoff** [comment]
cc @jrgm

**Comment by jrgm** [comment]
`{"Timestamp":1439754145936000000,"Logger":"fxa-content-server","Type":"route.500.Error: Command failed: fatal: Couldn't find remote ref tra\
in-44\n","Severity":2,"Pid":15118,"EnvVersion":"2.0"}`

**Comment by vladikoff** [comment]
@jrgm Ah I see, the experiments branch is causing this. Thanks

**Comment by vladikoff** [comment]
`latest` should probably use the `dev` branch of experiments, but need to think about that one. not sure how to configure that yet
