### ISSUE TITLE
experiments: latest.dev.lcip.org should use the "dev" branch of experiments

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-dev#185]
Need to find a way to point latest at https://github.com/mozilla/fxa-content-experiments/tree/dev

**Comment by vladikoff** [comment]
@jrgm @dannycoates I want to modify this part of:
```
environment=CONFIG_FILES="/data/fxa-content-server/server/config/awsbox.json,/data/fxa-content-server/server/config/production-experiments.json,/data/fxa-content-server/server/config/production-locales.json,/data/fxa-content-server/server/config/local.json"
user=app
```

in fxa-dev/roles/content/files/fxa-content-server.conf ( https://github.com/mozilla/fxa-dev/blob/3f6993e577538baffd6aa5f7bba770297ee0acec/roles/content/files/fxa-content-server.conf )

That should either point to a different experiments.json that has branch set to `dev` unlike https://github.com/mozilla/fxa-content-server/blob/master/server/config/production-experiments.json

Not sure what the best way to achieve that

**Comment by jrgm** [comment]
So, not sure what I'm missing, because it sounds like you're describing a good solution. `fxa-dev` box startup CONFIG_FILES points to a `config/fxa-dev-experiments.json` (or other name, maybe `dev-experiments.json`) instead of `config/production-experiments.json`. 

The fxa-dev-experiments.json file is basically set once and never changes.

**Comment by vladikoff** [comment]
@jrgm yeap we can add that, however how can we load `fxa-dev-experiments.json` only for latest?
 
in 
https://github.com/mozilla/fxa-dev/blob/3f6993e577538baffd6aa5f7bba770297ee0acec/roles/content/files/fxa-content-server.conf

**Comment by jrgm** [comment]
Ah, you mean use dev on latest but something else on `stable.dev.lcip.org`? (Any other fxa-dev box should default to using dev just like latest). 

If it's not possible already, we could add a variable (default value 'dev') to ansible, similar to the way that git fxa-* repos are checked out on master by default, but can use a specific git sha as required.

**Comment by vladikoff** [comment]
Closing this for now unless this is really needed. If you need "latest" experiments on "latest" just update the https://github.com/mozilla/fxa-content-server/blob/master/server/config/production-experiments.json in `master` to track the new branch for the new train
