### ISSUE TITLE
Dynamically generate OIDC keys at stack build time

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-dev#212]
In https://github.com/mozilla/fxa-dev/pull/207 we added a static, publicly-visible-in-our-github-repo key for signing OIDC assertions.  That'll do for a spell since this is only a dev server, but I think we should replace it with a dynamically generated key as a matter of good hygiene.

-----------------

- [x] Update OAuth Server to generate a keypair in a postinstall script, and use that in lib/config.js
- [x] Update fxa-dev by removing the `openid.key` and `openid.oldKey` configs

**Comment by vladikoff** [comment]
@seanmonstar to mentor :D
