### ISSUE TITLE
Deploy a box that works with a local content server

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-dev#213]
This is probably going to involve a lot of config changes.

For circle-ci we currently use a custom fxa-local-dev box to run functional tests.
We need to get rid of it because that box is a quick hack.

Ref http://fxadeploybox.dev.lcip.org:9000/

**Comment by vladikoff** [comment]
cc @vbudhram you asked about CircleCi failures, see comment above. Using fxa-dev for circle ci might fix all the problems!

**Comment by vbudhram** [comment]
@vladikoff, hopefully no more restarting circleci :)
