### ISSUE TITLE
CDN hostname should be on the lcip.org domain.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-dev#235]
Currently the CDN is hosted on a cloudfront.net domain. We need the lcip.org certs uploaded to Cloudfront and the Cloudfront ansible configuration updated to support custom domains.

**Comment by vladikoff** [comment]
from meeting: we talked about this in the server meeting, do you have a link about that needs to change in the ansible config?

**Comment by shane-tomlinson** [comment]
Ya, we need to use "Custom Domain" support - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-cloudfront.html#scenario-cloudfront-customorigin

To do so, we'll have to have our lcip.org cert available to use on Cloudfront. When setting up Cloudfront manually, the lcip.org cert was unavailable.

**Comment by vladikoff** [comment]
Need to fetch cert id by name to make it work...

**Comment by vladikoff** [comment]
A bit related to https://github.com/mozilla/fxa-dev/issues/213
