### ISSUE TITLE
different services should use distinct hostnames to better approximate production

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-dev#240]
Right now all services use the same hostname on AWS, routing to individual services is done by looking at the path. This arrangement makes testing CORS impossible since CORS preflight requests are only made when XHR requests are made cross domain.

**Comment by shane-tomlinson** [comment]
@jrgm +1's this. :D

**Comment by vladikoff** [comment]
from mtg: closing, just like the other bug we closed earlier
