### ISSUE TITLE
OutOfProtocolError: API responded with non-json content-type: text/html errors during setup against https://stable.dev.lcip.org/auth/

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxa-dev#260]
See https://webqa-ci.mozilla.com/view/FxAPOM/job/fxapom.stage.saucelabs/943/console for more detail.

We're seeing the following when we run fxapom.stage.* jobs (from this suite: https://github.com/mozilla/fxapom/tree/9ca23e7e76becc14c518aa45f631e1be295f644b) against https://stable.dev.lcip.org/auth/ in Jenkins:

23:42:26 =========================== short test summary info ============================
23:42:26 FAIL tests/test_fxa_test_account.py::TestFxATestAccount::()::test_default_environment_should_be_dev
23:42:26 ==================================== ERRORS ====================================
23:42:26  ERROR at setup of TestFxATestAccount.test_new_account_pw_does_not_contain_numbers[https://stable.dev.lcip.org/auth/] 
23:42:26 [gw6] linux2 -- Python 2.7.9 /var/lib/jenkins/jobs/fxapom.stage.saucelabs/workspace/.venv/bin/python2.7
23:42:26 tests/conftest.py:27: in account
23:42:26     return FxATestAccount(request.param)
23:42:26 fxapom/fxapom.py:59: in __init__
23:42:26     self.session = self.client.create_account(self.account.email, self.password)
23:42:26 .venv/lib/python2.7/site-packages/PyFxA-0.2.0-py2.7.egg/fxa/core.py:63: in create_account
23:42:26     resp = self.apiclient.post(url, body)
23:42:26 .venv/lib/python2.7/site-packages/PyFxA-0.2.0-py2.7.egg/fxa/_utils.py:299: in post
23:42:26     return self.request("POST", url, json, **kwds)
23:42:26 .venv/lib/python2.7/site-packages/PyFxA-0.2.0-py2.7.egg/fxa/_utils.py:231: in request
23:42:26     raise fxa.errors.OutOfProtocolError(msg.format(content_type))
23:42:26 E   OutOfProtocolError: API responded with non-json content-type: text/html
23:42:26  ERROR at setup of TestFxATestAccount.test_create_new_account[https://stable.dev.lcip.org/auth/] 
23:42:26 [gw10] linux2 -- Python 2.7.9 /var/lib/jenkins/jobs/fxapom.stage.saucelabs/workspace/.venv/bin/python2.7
23:42:26 tests/conftest.py:27: in account
23:42:26     return FxATestAccount(request.param)
23:42:26 fxapom/fxapom.py:59: in __init__
23:42:26     self.session = self.client.create_account(self.account.email, self.password)
23:42:26 .venv/lib/python2.7/site-packages/PyFxA-0.2.0-py2.7.egg/fxa/core.py:63: in create_account
23:42:26     resp = self.apiclient.post(url, body)
23:42:26 .venv/lib/python2.7/site-packages/PyFxA-0.2.0-py2.7.egg/fxa/_utils.py:299: in post
23:42:26     return self.request("POST", url, json, **kwds)
23:42:26 .venv/lib/python2.7/site-packages/PyFxA-0.2.0-py2.7.egg/fxa/_utils.py:231: in request
23:42:26     raise fxa.errors.OutOfProtocolError(msg.format(content_type))
23:42:26 E   OutOfProtocolError: API responded with non-json content-type: text/html
23:42:26 =================================== FAILURES ===================================
23:42:26 __________ TestFxATestAccount.test_default_environment_should_be_dev ___________
23:42:26 [gw1] linux2 -- Python 2.7.9 /var/lib/jenkins/jobs/fxapom.stage.saucelabs/workspace/.venv/bin/python2.7
23:42:26 tests/test_fxa_test_account.py:19: in test_default_environment_should_be_dev
23:42:26     account = FxATestAccount()
23:42:26 fxapom/fxapom.py:59: in __init__
23:42:26     self.session = self.client.create_account(self.account.email, self.password)
23:42:26 .venv/lib/python2.7/site-packages/PyFxA-0.2.0-py2.7.egg/fxa/core.py:63: in create_account
23:42:26     resp = self.apiclient.post(url, body)
23:42:26 .venv/lib/python2.7/site-packages/PyFxA-0.2.0-py2.7.egg/fxa/_utils.py:299: in post
23:42:26     return self.request("POST", url, json, **kwds)
23:42:26 .venv/lib/python2.7/site-packages/PyFxA-0.2.0-py2.7.egg/fxa/_utils.py:231: in request
23:42:26     raise fxa.errors.OutOfProtocolError(msg.format(content_type))
23:42:26 E   OutOfProtocolError: API responded with non-json content-type: text/html
23:42:26 ================= 1 failed, 7 passed, 2 error in 28.65 seconds =================

@davehunt knows this suite much better than I, @jrgm might be of help, and @rfk has also always been helpful

**Comment by rfk** [comment]
FWIW I wasn't able to reproduce this by hand:

```
>>> c = fxa.core.Client(server_url="https://stable.dev.lcip.org/auth")
>>> s = c.create_account("ryan-threeee@rfk.id.au", "iheartlemurs")
>>> s.get_email_status()
{u'emailVerified': False, u'verified': False, u'email': u'ryan-threeee@rfk.id.au', u'sessionVerified': True}
```

Does this fail every time, or intermittently?

**Comment by stephendonner** [comment]
Fails every time in our automation: https://webqa-ci.mozilla.com/view/FxAPOM/

Not sure what's going on - we appear to be/should be on the latest w/pyfxa, too.

**Comment by shane-tomlinson** [comment]
I'm closing this down, @jrgm restarted the servers via supervisorctl. He is investigating why there was a problem in the first place, but this bug as it stands is fixed.

**Comment by jrgm** [comment]
Final resolution was that I had switched the instance size to t2.small which didn't have enough RAM to support a couple of dozen service daemons all running on one box. Changed the size to t2.medium.
