### ISSUE TITLE
NPM running out of space error when deploying profile server

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-dev#262]
Received this error when trying to deploy a dev box, using auth-server sha `8969fbeda8b81128f4c84934e6d74fa55beca708`

```bash
ERR! nospc ENOSPC, open '/data/fxa-profile-server/node_modules/mozlog/test/schema.json'\nnpm ERR! nospc This is most likely not a problem with npm itself\nnpm ERR! nospc and is related to insufficient space on your system.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /data/fxa-profile-server/npm-debug.log
```

The instance is a T2.small which says it has 30GB of hard drive space? Any ideas what might cause this?

cc @jrgm

**Comment by shane-tomlinson** [comment]
Dup of #261?

**Comment by vbudhram** [comment]
@shane-tomlinson Yea, believe it was. Looks like I was using and elder version of fxa-dev with smaller instance sizes, pulled down latest and redeployed and it works! Closing...
