### ISSUE TITLE
Run regular loadtests against latest.dev?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-dev#278]
We had some bustage in train-70 due to memory usage issues that appeared under load.  I wonder if we could avoid this in future by regularly running out loadtests against latest.dev.  If we discover that the server has died because of an out-of-memory issue, well, we've got something to investigate before @jrgm and @jbuck attempt to deploy it.

Thoughts?

**Comment by vladikoff** [comment]
👍  we can spin another nightly circle-ci box 👀

**Comment by vladikoff** [comment]
@rfk we need to chat about the tests in https://github.com/mozilla/fxa-auth-server/tree/master/test/load seems like there are problems with `make build` with recent changes to  PyFxA

**Comment by vladikoff** [comment]
from mtg: @rfk tried this and it worked for him....

**Comment by rfk** [comment]
I suspect the problem is using the system python on OSX; if you `brew install python` to get a more up-to-date version it should work OK.

**Comment by vladikoff** [comment]
🗡
