### ISSUE TITLE
Is the "well-known" config wrong for *.dev.lcip.org deploys?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-dev#286]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1313731

Stages has the /v1 but stable does not.

```
{"auth_server_base_url":"https://api-accounts.stage.mozaws.net/v1
```

**Comment by rfk** [comment]
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1313731#c6 we decided that all URLs should *exclude* the /v1, so the setup in fxa-dev boxes is fine.
