### ISSUE TITLE
Database server not stable on fxa-dev boxes

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-dev#290]
We noticed several requests being dropped by the database server when tested by the Circle CI box.

Ref 1 : https://github.com/mozilla/fxa-auth-server/issues/1553

Ref 2: fxa-oauth-console fails to look up bear tokens. I restarted it all the servers and it started working again.

@jbuck @jrgm thoughts?

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-auth-db-mysql/issues/194

**Comment by vladikoff** [comment]
closing in favour of other 2-3 issues
