### ISSUE TITLE
[docker] fix startup race between oauth and oauth-internal

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-dev#304]
I did one fix to have oauth-internal not create the mysql schema. But the race still exists, since oauth-internal will start before oauth has finished creating the schema. Need to `wait_for` the oauth port listener to respond before starting the oauth-internal container. 

However, this is low-priority for a fix. Within 10 minutes the cronjob will run and successfully start the oauth-internal container, which will now find the right schema version.

**Comment by vladikoff** [comment]
I think this was fixed
