### ISSUE TITLE
503 from auth-server on nightly.dev.lcip.org

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-dev#330]
I'm currently getting "unexpected error" when trying to create an account on https://nightly.dev.lcip.org.  Watching the network request log, it is receiving a 503 during the CORS pre-flight request to `OPTIONS https://nightly-auth.dev.lcip.org/v1/account/create`.

I also get a 503 when browsing directly to https://nightly-auth.dev.lcip.org/

**Comment by vladikoff** [comment]
cc @jrgm

**Comment by vladikoff** [comment]
FixeD!
