### ISSUE TITLE
Use a mozilla/123done dockerhub image

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-dev#359]
Currently, it uses jrgm/123done which is built from github/mozilla/123done but y'know.... buses and stuff. 

https://github.com/mozilla/fxa-dev/search?utf8=%E2%9C%93&q=jrgm%2F123done&type=

**Comment by jrgm** [comment]
Or, actually. Facepalm. It's not building github/mozilla/123done. Argh.

**Comment by vladikoff** [comment]
Yea I think we have to build it manually these days or something

**Comment by jrgm** [comment]
Okay, to be clear, the image we use on fxa-dev instances is built from `abc14ad 2017-05-11 11:33:50` of github/mozilla/123done. So missing two commits from last year, and @rfk and @stomlinson's commits from the last week.

I'll switch to getting a dockerhub mozilla/123done autobuild and change fxa-dev to docker pull from that.

Is it "Argh" of "fuuuu...".
