### ISSUE TITLE
Add the pairing channel server to the list of servers to run 

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-dev#395]
This repo: https://github.com/mozilla-services/pairsona/, the server to run is in https://github.com/mozilla-services/pairsona/tree/master/channelserver

**Comment by philbooth** [comment]
@shane-tomlinson, we're taking a wild stab in the dark and putting this in next with your face on.

**Comment by shane-tomlinson** [comment]
@rfk has already put some stuff together in #398, taking my face off of this!

**Comment by vladikoff** [comment]
This was merged
