### ISSUE TITLE
email notifications on fxa-dev build fails

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-dev#40]
Earlier, it looks like the latest/nightly boxes were stuck on older versions of fxa-content-server repo (specifically https://github.com/mozilla/fxa-content-server/commit/4b1c51022f0169128add0c25e29e5d192a433231 &mdash; @ckarlof manually kicked off some server magic to get it refreshed).

Not sure what reporting we have on the fxa-dev boxes or if they're sending out emails on failures. It'd be nice to add the cloud services QA alias added to notifications, and whatever devs also want to be notified.

@jrgm noted in IRC:
> _So, somehow /data/fxa-content-server/server/templates/pages/dist is owned by root, and the app user is not able to rebuild over that with grunt build._

**Comment by shane-tomlinson** [comment]
@vladikoff believes this was fixed, closing.
