### ISSUE TITLE
Increase leniency for OAuth requests to dev stack to get sync keys

### ISSUE THREAD

**Issue by thomcc** [mozilla/fxa-dev#400]
At the moment we need to use a specific set of redirects (such as the lockbox redirect url) in order to get the sync keys in the OAuth flow.

This makes sense, but makes some kinds of automated testing harder, so it would be nice if it were not required on the dev stack.

**Comment by shane-tomlinson** [comment]
@thomcc - do your redirect_uri's change often? If not, we could create a new OAuth relier for you to test with.

**Comment by thomcc** [comment]
I'd like to be able to use something on localhost, so that the whole process can be automated during a test run.

**Comment by thomcc** [comment]
I found a way to work around this, so nevermind.
