### ISSUE TITLE
Use `docker system prune` for cleaning up old docker images

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-dev#409]
So as we don't gradually fill up all the disk space on the boxes.  This is what I did by hand recently to remove untagged docker images:

```
docker images | grep '<none>' | tr -s ' ' | cut -d ' ' -f 3 | xargs docker rmi
```

There may be a nicer way tho.

**Comment by jbuck** [comment]
If there's a new enough version of docker on the instance, [docker system prune](https://docs.docker.com/engine/reference/commandline/system_prune/) will clean everything up

**Comment by rfk** [comment]
Nice, this appears to be available:

```
$ docker system prune --force
Total reclaimed space: 0B
```

**Comment by rfk** [comment]
Doing `docker system prune --force --all` removed another 30MB or so of non-image-related state as well 👍

**Comment by jrgm** [comment]
Actually, there's always been a role [docker-gc](https://github.com/mozilla/fxa-dev/blob/docker/aws/roles/docker-gc/tasks/main.yml) that does effectively what @rfk suggested in the opening comment. (Not that switching that to use `docker system prune` shouldn't be done). But, at least on `latest`, the ansible-playbook run is erroring out part way through and preventing the run of `docker-gc`. So, I fix that. (Error is `'oauth_internal_private_port' is undefined`).

**Comment by rfk** [comment]
Oh nice, thanks @jrgm! I updated the bug title and filed https://github.com/mozilla/fxa-dev/pull/411 accordingly.

**Comment by jrgm** [comment]
The other issue was https://github.com/mozilla/fxa-dev/pull/410, and then some others. Pruning works again, but could be switched to `docker system prune`.
