### ISSUE TITLE
Token verify issue with fxa train 151

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa-dev#500]
Login isn't working on the latest FxA release, some kind of token verification issue.

Pasting in the slack thread:

jrgm  1 day ago
so anyways, this doesn’t work on latest. It did work right after 150 was cut from master, but something else has changed I guess.
jrgm  24 hours ago
@Jared Hirsch ^^
jrgm  23 hours ago
(Correction: I meant after 149, and with the oauth->auth change landed on master).
jrgm  23 hours ago
the symptom now is the browser fetches an access_token ok, but then when it immediately sends it back to /profile/v1/profile a 401 is returned with reason ‘Not Found’. Ring any bells?
Jared Hirsch  23 hours ago
That's odd. I can't think of anything. Maybe @dcoates ran into something when doing the conversion?
dcoates  23 hours ago
where? stable or latest?
jrgm  23 hours ago
latest
jrgm  23 hours ago
stable is disabled from updating.
jrgm  23 hours ago
I think it’s probably has to do with verifying the token, yeah.
jrgm  23 hours ago
well, that’s slightly obvious of course.
dcoates  23 hours ago
i’ll take a look
dcoates  22 hours ago
i think our nginx rewrite is wrong…? :fry-2:. Having auth-server at /auth is a real pita
jrgm  22 hours ago
I could believe that.
jrgm  22 hours ago
So, quick question: is /v1/verify a route on the auth server now?
dcoates  22 hours ago
yes. all oauth routes are
jrgm  22 hours ago
So what I see is after sucessfully calling https://latest.dev.lcip.org/auth/v1/account/login and https://latest.dev.lcip.org/auth/v1/recovery_email/status
jrgm  22 hours ago
a request is made to POST https://latest.dev.lcip.org/auth/v1/oauth/token
jrgm  22 hours ago
which returns an access_token 91870a209600abf0efbaf91…
jrgm  22 hours ago
then a request to https://latest.dev.lcip.org/profile/v1/profile is made with Authorization: Bearer 91870a
jrgm  22 hours ago
in nginx logs I see that a request then goes to oauth-latest.dev.lcip.org “POST /v1/verify
jrgm  22 hours ago
which is 404
jrgm  22 hours ago
and latest.dev.lcip.org “GET /profile/v1/profile  is then 401
jrgm  22 hours ago
Should those tokens be in the fxa_oauth.tokens table?
dcoates  22 hours ago
yes
jrgm  21 hours ago
weird. I have mysql general log on on latest, and when I trigger the request to https://latest.dev.lcip.org/auth/v1/oauth/token, I see in insert into tokens... in the log, but the token value going to db is not what is returned to the http request.
jrgm  21 hours ago
I’m probably forgetting, or things changed, but those Bearer tokens are just a straight lookup?
dcoates  21 hours ago
it should be… https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/oauth/token.js#L41
packages/fxa-auth-server/lib/oauth/token.js:41

  const token = await db.getAccessToken(await exports.getTokenId(accessToken));

<https://github.com/mozilla/fxa|mozilla/fxa>mozilla/fxa | Added by GitHub
dcoates  21 hours ago
it could be something with the jwt sub or aud
jrgm  21 hours ago
so I put an strace on key_server.js
jrgm  21 hours ago
It reads the incoming verify request
jrgm  21 hours ago
20:30:24.421553 read(27, “POST /auth/v1/verify
jrgm  21 hours ago
and almost immediately logs a 404/999
jrgm  21 hours ago
20:30:24.422772 write(2,
jrgm  21 hours ago
i.e., it doesn’t even try to talk to fxa_oauth
Jared Hirsch  39 minutes ago
@jrgm hey, how's this going?
Jared Hirsch  40 minutes ago
Let me know what I can do to help
jrgm  5 minutes ago
Yeah. So I haven’t looked more since the last comments I made. (I have to prep for a non-fxa db thang). If you wanted to look at the code relevant to what Danny pointed out that would be good.
jrgm  4 minutes ago
The token I was seeing was not a jwt, or it doesn’t match the pattern.
jrgm  2 minutes ago
The token, in hashed form, is in the db I think, but it bails before checking the db. So why doesn’t it like that token.

**Comment by jrgm** [comment]
So, that fixes the issue I was seeing previously. Thanks @dannycoates and @6a68 

(There's a bit of an oddity. Once you're authenticated, visiting `/` does a js-redirect to `/signin`. But that's doesn't strike me as related to oauth->auth).
