### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-dev#51]
In cloud services show and tell, it seems to be all the rage with the kids.

@st3fan says he has already converted the FxA infrastructure to Docker. Thoughts?

**Comment by vladikoff** [comment]
@st3fan do you have any `Dockerfile`s already available?

**Comment by st3fan** [comment]
@vladikoff I thought I had docker files on Github but I think this project is on my home server, which currently sits in a moving box in storage. But I do remember that it was pretty trivial to get it up and running on Docker :-)

**Comment by vladikoff** [comment]
@st3fan ah that's fine, mostly I wanted to compare the Dockerfiles I made with the ones you had.
Thanks for the reply!

**Comment by vladikoff** [comment]
The Devops team is on this, we will track progress with them first and then maybe migrate some of those dockerfiles here
