### ISSUE TITLE
Monitor our dev environments and alert on outage

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-dev#57]
I think Jenkins is already running the functional tests against latest, but we should maybe add the remote auth server tests, too, and make sure the proper people are notified.

**Comment by rfk** [comment]
@vladikoff has this been replaced by TeamCity or equivalent?

**Comment by vladikoff** [comment]
@rfk not really, we need some monitoring tool (a CI might not be the best choice here). something that pings https://oauth-latest.dev.lcip.org/console/login for instance and makes sure it returns 200

Maybe something like https://uptimerobot.com/

**Comment by vladikoff** [comment]
Fixed via http://status.dev.lcip.org/
