### ISSUE TITLE
Make first vagrant up work for a new contributor. 

### ISSUE THREAD

**Issue by renoirb** [mozilla/fxa-dev#81]
## How to resolve

**Either**
* Link to possible vagrantbox.es
* Provide link to customized image

**OR**

* Install steps ends up with a **fully working** independent deployment of FxA
* (optional) do not require initial database

# Building the VM:

## Related notes

* [Making work fxa-dev Vagrant VM from a vanilla fedora20 VM without database.](https://gist.github.com/WebPlatformDocs/7f0d8c32cc4cbbf718b9) that were done **after** the steps in this issue.

## Initial procedure

**Note** Progress is described in the comment thread.

This procedure assumes one doesn’t have access to `dcoates/fedora20` `config.vm.box` Vagrant box.

**Environment:**

* MacOS X as host
* Vagrant v1.6.5
* VirtualBox v4.3.6
* Installed Ansible through *brew* on Mac OS X host

### Steps

0. Install Ansible

        brew install ansible

1. Adjust `Vagrantfile` with:

        config.vm.box = "fedora20"
        config.vm.box_url = "https://dl.dropboxusercontent.com/u/15733306/vagrant/fedora-20-netinst-2014_01_05-minimal-puppet-guestadditions.box"

2. Boot the VM for the first time

  First time it fails, its OK.

        make

3. Fun in the VM the following:

        vagrant ssh

  Inside the VM

        sudo -s
        yum update
        yum install -y npm git ansible

4. Halt the VM, restart the process

        exit
    
  Back on the host;

        vagrant halt
        make 

5. Add what’s missing inside the VM

  Inside the VM, as root;

        adduser app
        mkdir /data
        chown -R app:app /data/
        easy_install supervisor
        npm install -g grunt-cli

6. Get the code

  On the host;

        make update-code

  Wait.

  It breaks at `fxa-auth-server`, see [npm-debug.log](https://gist.github.com/WebPlatformDocs/61ba9af001b6225596c7)

7. Breaks halfway

  Here is how `/data` looks like

        drwxr-xr-x. 10 app app 4096 Dec  3 16:14 fxa-auth-db-server
        drwxr-xr-x.  6 app app 4096 Dec  3 16:11 fxa-auth-mailer
        drwxr-xr-x. 14 app app 4096 Dec  3 16:45 fxa-auth-server
        drwxr-xr-x. 10 app app 4096 Dec  3 16:17 fxa-content-server
        drwxr-xr-x. 10 app app 4096 Dec  3 16:22 fxa-customs-server

8. Delete an try again

  After reading the  [npm-debug.log](https://gist.github.com/WebPlatformDocs/61ba9af001b6225596c7). It mentionned to delete and try again.

  Inside the VM;
        rm -rf /root/tmp/npm-

  Trying again from the host;

        make update-code

  Got a different error message. It talked about missing `gmp.h`. 

  ![screen shot 2014-12-03 at 5 19 53 pm](https://cloud.githubusercontent.com/assets/296940/5289954/ae5a218c-7b10-11e4-8ea2-fdc9aad61dc5.png)

        yum install -y gmp.x86_64 gmp-devel.x86_64

10. Another `make update-code` attempt

  It worked! /o/

![screen shot 2014-12-03 at 5 20 04 pm](https://cloud.githubusercontent.com/assets/296940/5289963/bd2eaae8-7b10-11e4-987f-04ca15117406.png)

11. ... and a few `make update`

**Comment by rfk** [comment]
I'm going through and cleaning up some of our old bugs.  @renoirb do you still have interest in this?  IIUC none of the FxA core devs are using the vagrant stuff in this repo any longer.

**Comment by rfk** [comment]
I'm going to close this out since the vagrant stuff in that repo is essentially unmaintaned.  We may revisit with e.g. a docker based flow in the future.
